import type { SpaceSummary, TaskItem } from "./types";

export const spaces: SpaceSummary[] = [
  {
    name: "[LMN] Originais",
    active: 16,
    color: "blue",
    folders: [
      {
        name: "PLANEJAMENTO",
        active: 16,
        lists: [
          { name: "ORIGINAIS", active: 16, folderName: "PLANEJAMENTO" },
          { name: "PROJETOS BACKLOG", active: 0, folderName: "PLANEJAMENTO" },
          { name: "Calendario 2025 - Plataforma", active: 0, folderName: "PLANEJAMENTO" },
        ],
      },
    ],
    listsWithoutFolder: [],
  },
  {
    name: "[LMN] Producoes",
    active: 1,
    color: "green",
    folders: [],
    listsWithoutFolder: [
      { name: "Captacao de recursos", active: 1 },
      { name: "Festivais e Premios", active: 0 },
      { name: "Cadastros ANCINE", active: 0 },
      { name: "Acoes Gerais", active: 0 },
    ],
  },
];

export const tasks: TaskItem[] = [
  {
    id: "86agx406v",
    externalId: "86agx406v",
    code: "CLK-00",
    title: "#2-94 | Natal Amarelo IV [Cidade Amarela]",
    description: "Tarefa pai para transporte, hospedagem e entregas locais.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    status: "in_progress",
    priority: "high",
    assignees: ["Aline Marques", "Dudu Lorenzetti"],
    dueDate: "2026-07-12",
    startDate: "2026-07-01",
    tags: ["Originais", "Producao"],
    customFields: {
      "Campanha ADS": "Cidade Amarela",
      Editoria: "Originais",
      Formato: "Serie",
    },
    comments: 4,
    subtasksDone: 2,
    subtasksTotal: 5,
    sourceUrl: "https://app.clickup.com/t/86agx406v",
    taskType: "task",
  },
  {
    id: "86aj6419u",
    externalId: "86aj6419u",
    code: "CLK-04",
    title: "Rodoviario - dudu [IDA - 12/07]",
    description: "Compra e confirmacao da ida.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    parentTask: "#2-94 | Natal Amarelo IV [Cidade Amarela]",
    parentExternalId: "86agx406v",
    isSubtask: true,
    status: "in_progress",
    priority: "normal",
    assignees: ["Aline Marques"],
    dueDate: "2026-07-04",
    startDate: "2026-07-02",
    tags: ["Logistica", "ClickUp"],
    comments: 2,
    subtasksDone: 0,
    subtasksTotal: 0,
    sourceUrl: "https://app.clickup.com/t/86aj6419u",
    taskType: "subtask",
  },
  {
    id: "86agx409w",
    externalId: "86agx409w",
    code: "CLK-05",
    title: "Hospedagem",
    description: "Definir hotel, quartos e aprovacao final.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    parentTask: "#2-94 | Natal Amarelo IV [Cidade Amarela]",
    parentExternalId: "86agx406v",
    isSubtask: true,
    status: "todo",
    priority: "normal",
    assignees: ["Aline Marques"],
    dueDate: "2026-07-05",
    startDate: "2026-07-03",
    tags: ["Hospedagem", "Logistica"],
    customFields: {
      "Campanha ADS": "Cidade Amarela",
      Formato: "Logistica",
    },
    comments: 1,
    subtasksDone: 1,
    subtasksTotal: 2,
    sourceUrl: "https://app.clickup.com/t/86agx409w",
    taskType: "subtask",
  },
  {
    id: "86ahotel01",
    externalId: "86ahotel01",
    code: "CLK-05A",
    title: "Confirmar bloqueio de quartos",
    description: "Aguardando retorno do hotel base.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    parentTask: "Hospedagem",
    parentExternalId: "86agx409w",
    isSubtask: true,
    status: "review",
    priority: "normal",
    assignees: ["Aline Marques"],
    dueDate: "2026-07-06",
    startDate: "2026-07-04",
    tags: ["Hospedagem"],
    comments: 1,
    subtasksDone: 1,
    subtasksTotal: 1,
    sourceUrl: "https://app.clickup.com/t/86ahotel01",
    taskType: "subtask",
  },
  {
    id: "86ahotel02",
    externalId: "86ahotel02",
    code: "CLK-05B",
    title: "Enviar rooming list",
    description: "Lista completa com nomes e documentos.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    parentTask: "Confirmar bloqueio de quartos",
    parentExternalId: "86ahotel01",
    isSubtask: true,
    status: "todo",
    priority: "low",
    assignees: ["Dudu Lorenzetti"],
    dueDate: "2026-07-07",
    startDate: "2026-07-05",
    tags: ["Hospedagem"],
    comments: 0,
    subtasksDone: 0,
    subtasksTotal: 1,
    sourceUrl: "https://app.clickup.com/t/86ahotel02",
    taskType: "subtask",
  },
  {
    id: "86ahotel03",
    externalId: "86ahotel03",
    code: "CLK-05C",
    title: "Anexar comprovantes",
    description: "Ultima camada da cadeia de subtarefas.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    parentTask: "Enviar rooming list",
    parentExternalId: "86ahotel02",
    isSubtask: true,
    status: "todo",
    priority: "low",
    assignees: ["Dudu Lorenzetti"],
    dueDate: "2026-07-08",
    startDate: "2026-07-06",
    tags: ["Financeiro"],
    comments: 0,
    subtasksDone: 0,
    subtasksTotal: 1,
    sourceUrl: "https://app.clickup.com/t/86ahotel03",
    taskType: "subtask",
  },
  {
    id: "86ahotel04",
    externalId: "86ahotel04",
    code: "CLK-05D",
    title: "Conferir NF final",
    description: "Quinto nivel para validacao da estrutura.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    parentTask: "Anexar comprovantes",
    parentExternalId: "86ahotel03",
    isSubtask: true,
    status: "todo",
    priority: "low",
    assignees: ["Dudu Lorenzetti"],
    dueDate: "2026-07-09",
    startDate: "2026-07-07",
    tags: ["Financeiro"],
    comments: 0,
    subtasksDone: 0,
    subtasksTotal: 0,
    sourceUrl: "https://app.clickup.com/t/86ahotel04",
    taskType: "subtask",
  },
  {
    id: "86aj75root",
    externalId: "86aj75root",
    code: "CLK-11",
    title: "#2-73 | Brasil de todos os Santos II [SUL]",
    description: "Concentrador de entregas do projeto.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    status: "in_progress",
    priority: "high",
    assignees: ["Davi Moura"],
    dueDate: "2026-07-10",
    startDate: "2026-07-01",
    tags: ["Originais"],
    comments: 3,
    subtasksDone: 1,
    subtasksTotal: 2,
    sourceUrl: "https://app.clickup.com/t/86aj75root",
    taskType: "task",
  },
  {
    id: "86aj75zzm",
    externalId: "86aj75zzm",
    code: "CLK-01",
    title: "Cazarre",
    description: "Acompanhamento do material principal.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    parentTask: "#2-73 | Brasil de todos os Santos II [SUL]",
    parentExternalId: "86aj75root",
    isSubtask: true,
    status: "in_progress",
    priority: "high",
    assignees: ["Davi Moura"],
    dueDate: "2026-07-01",
    startDate: "2026-06-29",
    tags: ["Pagamento", "ClickUp"],
    comments: 0,
    subtasksDone: 0,
    subtasksTotal: 0,
    sourceUrl: "https://app.clickup.com/t/86aj75zzm",
    taskType: "subtask",
  },
  {
    id: "86ad82jw6",
    externalId: "86ad82jw6",
    code: "CLK-09",
    title: "Log",
    description: "Registro consolidado do projeto.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    parentTask: "#2-73 | Brasil de todos os Santos II [SUL]",
    parentExternalId: "86aj75root",
    isSubtask: true,
    status: "in_progress",
    priority: "normal",
    assignees: ["Dudu Lorenzetti"],
    dueDate: "2026-07-09",
    startDate: "2026-07-02",
    tags: ["Log", "Originais"],
    comments: 0,
    subtasksDone: 0,
    subtasksTotal: 0,
    sourceUrl: "https://app.clickup.com/t/86ad82jw6",
    taskType: "subtask",
  },
  {
    id: "86ad82root",
    externalId: "86ad82root",
    code: "CLK-12",
    title: "#2-75 | O caminho de Marcelo Camara",
    description: "Agrupador editorial para aprovacoes e retornos.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    status: "review",
    priority: "normal",
    assignees: ["Jordana Bastos"],
    dueDate: "2026-07-11",
    startDate: "2026-07-01",
    tags: ["Editorial"],
    comments: 2,
    subtasksDone: 0,
    subtasksTotal: 1,
    sourceUrl: "https://app.clickup.com/t/86ad82root",
    taskType: "task",
  },
  {
    id: "86ad82u0x",
    externalId: "86ad82u0x",
    code: "CLK-02",
    title: "RP [agradecimentos] | Marcelinho",
    description: "Texto final para revisão.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    parentTask: "#2-75 | O caminho de Marcelo Camara",
    parentExternalId: "86ad82root",
    isSubtask: true,
    status: "in_progress",
    priority: "normal",
    assignees: ["Jordana Bastos"],
    dueDate: "2026-07-02",
    startDate: "2026-06-30",
    tags: ["ClickUp", "Originais"],
    comments: 0,
    subtasksDone: 0,
    subtasksTotal: 0,
    sourceUrl: "https://app.clickup.com/t/86ad82u0x",
    taskType: "subtask",
  },
  {
    id: "86agtxroot",
    externalId: "86agtxroot",
    code: "CLK-13",
    title: "#2-96 | Fe Asiatica",
    description: "Coordenacao geral do material de guia.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    status: "in_progress",
    priority: "normal",
    assignees: ["Jordana Bastos"],
    dueDate: "2026-07-13",
    startDate: "2026-07-02",
    tags: ["Originais"],
    comments: 1,
    subtasksDone: 0,
    subtasksTotal: 1,
    sourceUrl: "https://app.clickup.com/t/86agtxroot",
    taskType: "task",
  },
  {
    id: "86agtxuw1",
    externalId: "86agtxuw1",
    code: "CLK-06",
    title: "Guia - Amanda e Marcella",
    description: "Acompanhamento do guia final.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    parentTask: "#2-96 | Fe Asiatica",
    parentExternalId: "86agtxroot",
    isSubtask: true,
    status: "in_progress",
    priority: "normal",
    assignees: ["Jordana Bastos"],
    dueDate: "2026-07-06",
    startDate: "2026-07-02",
    tags: ["Guia", "Originais"],
    comments: 0,
    subtasksDone: 0,
    subtasksTotal: 0,
    sourceUrl: "https://app.clickup.com/t/86agtxuw1",
    taskType: "subtask",
  },
  {
    id: "86adq8root",
    externalId: "86adq8root",
    code: "CLK-14",
    title: "TASKS Producao",
    description: "Estrutura de demandas compartilhadas com producao.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    status: "todo",
    priority: "high",
    assignees: ["Jordana Bastos"],
    dueDate: "2026-07-14",
    startDate: "2026-07-03",
    tags: ["Pipeline"],
    comments: 1,
    subtasksDone: 0,
    subtasksTotal: 1,
    sourceUrl: "https://app.clickup.com/t/86adq8root",
    taskType: "task",
  },
  {
    id: "86adq8qx3",
    externalId: "86adq8qx3",
    code: "CLK-07",
    title: "Fazer CRT conteudos PRIME",
    description: "CRT pendente para pacote PRIME.",
    space: "[LMN] Originais",
    folder: "PLANEJAMENTO",
    list: "ORIGINAIS",
    parentTask: "TASKS Producao",
    parentExternalId: "86adq8root",
    isSubtask: true,
    status: "in_progress",
    priority: "high",
    assignees: ["Jordana Bastos"],
    dueDate: "2026-07-07",
    startDate: "2026-07-03",
    tags: ["CRT", "Prime"],
    comments: 0,
    subtasksDone: 0,
    subtasksTotal: 0,
    sourceUrl: "https://app.clickup.com/t/86adq8qx3",
    taskType: "subtask",
  },
  {
    id: "86afz9aq7",
    externalId: "86afz9aq7",
    code: "PROD-01",
    title: "Website",
    description: "Landing page de captação.",
    space: "[LMN] Producoes",
    list: "Captacao de recursos",
    status: "todo",
    priority: "normal",
    assignees: ["Dudu Lorenzetti"],
    dueDate: "2026-07-16",
    startDate: "2026-07-05",
    tags: ["Captação"],
    comments: 0,
    subtasksDone: 0,
    subtasksTotal: 0,
    sourceUrl: "https://app.clickup.com/t/86afz9aq7",
    taskType: "task",
  },
];
